config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  get 'signup', to: 'users#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :tasks, only: [:create, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception
  
  private
  
  def require_user_logged_in
    unless logged_in?
      flash[:danger] = 'ログインして下さい'
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインしました'
      redirect_to root_url
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードが間違っています'
      @email = params[:session][:email]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = 'タスクが正常に投稿されました'
      redirect_to root_url
    else
      flash.now[:denger] = 'タスクが投稿されませんでした'
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page]).per(10)
      render 'toppages/index'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @task.update(task_params)
      flash[:success] = 'タスクが正常に更新されました'
      redirect_to @task
    else
      flash.now[:denger] = 'タスクが更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    
    flash[:success] = 'タスクは正常に削除されました'
    redirect_to tasks_url
  end
  
  private
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @task = current_user.tasks.build
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page]).per(10)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました'
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TaskList</a>
      </div>
    
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></a></li>
          <% else %>
            <li><%= link_to 'ユーザー登録', new_user_path %></li>
            <li><%= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tasklist</title>
    
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :content, 'タスク' %>
    <%= f.text_field :content, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :status, 'ステータス' %>
    <div>
      <%= f.select :status, ['未着手', '着手', '完了'], :include_blank => true, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit '投稿', class:"btn btn-primary" %>
<% end %>

app/views/tasks/_tasks.html.erb
<% if tasks.any? %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>タスク</th>
        <th>ステータス</th>
        <th>投稿日時</th>
      </tr>
    </thead>
    <tbody>
      <% tasks.each do |task| %>
        <tr>
          <td><%= link_to task.content, task %></td>
          <td><%= task.status %></td>
          <td><%= task.created_at.getlocal("+09:00").strftime('%Y/%m/%d %H:%M') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate tasks %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<header>
  <h1>タスク編集</h1>
</header>
<body>
  <%= render 'form', task: @task %>
  
</body>

app/views/tasks/show.html.erb
<header>
  <h1>タスク No.<%= @task.id %></h1>
</header>
<body>
  <table class="table table-bordered">
    <tr>
      <th>id</th>
      <td><%= @task.id %></td>
    </tr>
    <tr>
      <th>タスク</th>
      <td><%= @task.content %></td>
    </tr>
    <tr>
      <th>ステータス</th>
      <td><%= @task.status %></td>
    </tr>
  </table>
  
  <%= link_to '編集', edit_task_path(@task), class:"btn btn-default" %>
  <%= link_to '削除', @task, method: :delete, class:"btn btn-danger", data: { confirm: '本当に削除してよろしいですか？' } %>
</body>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="row">
    
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">新規タスク投稿</h3>
        </div>
        <div class="panel-body">
          <%= render 'tasks/form', task: @task %>
        </div>
      </div>
    </div>
    
    <div class="col-md-8">
      <h2><%= current_user.name %> さんのタスク一覧</h2>    
      <%= render 'tasks/tasks', tasks: @tasks %>
    </div>
    
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the TaskList!</h1>
    </div>
  </div>
  
  <div class="text-center">
    <div>
      <%= link_to 'ログイン', login_path, class:'btn btn-primary btn-lg' %>
    </div>
    <%= link_to 'はじめての方はこちら', signup_path %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード確認' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  
    <%= f.submit '登録', class:'btn btn-primary btn-block' %>
<% end %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>ユーザー登録</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= render 'form', user: @user %>
    <div class="text-center">
      <%= link_to '登録済みの方はこちら', login_path %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <h2><%= current_user.name %> さんのタスク一覧</h2>
</div>

<div>
  <ul class="nav nav-tabs nav-justified">
    <li><a href="#">未着手</a></li>
    <li><a href="#">着手</a></li>
    <li><a href="#">完了</a></li>
  </ul>
</div>